move DLP-based Schnorr signature to Module 2
adrianmcli/summer-contribution-program pull request #6
Opened 2023-09-08 15:58 UTC by jae-cuz

### Description

Distinguishing Schnorr signatures based on DLP and EC in Module 3, I suggest to move DLP-based Schnorr signature to Digital Signature section in Module 2.

### Related Issues

#4 

### Affected Tutorials

- Module Name: Module 2 & Module 3
- Section/Step: Digital Signatures / Schnorr Signatures and EdDSA

### Type of Change

- [ ] Typo/grammar fix
- [ ] Code correction (e.g., a bug in a code snippet)
- [ ] New tutorial or section
- [x] Other (please describe): section rearrangement

### Testing

I read the changed part of the document again.

### Checklist

- [x] I have performed a self-review of my own changes.
- [x] I have made corresponding changes to related documentation.

2023-09-08 17:18 UTC, adrianmcli requested changes
Just a slight grammatical change. Thanks!

2023-09-08 17:18 UTC, adrianmcli commented on MODULE_3.md
> +Schnorr signatures also can be extended to elliptic curve. A key benefit is their linear structure, which allows for multi-signature aggregation.
```suggestion
Schnorr signatures can also be extended to elliptic curves. A key benefit is their linear structure, which allows for multi-signature aggregation.
```

2023-09-09 04:08 UTC, jae-cuz commented
Sure :) Thanks for catching that!

2023-09-09 15:43 UTC, merged

2023-09-09 15:43 UTC, adrianmcli commented
thanks @jae-cuz
btw, if you write "Fixes #4" in the PR description, the merging of the PR will automatically close the issue as well.

See here for more info: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue